default_platform(:ios)

platform :ios do
  desc "Builds the app without a provisioning profile"
  lane :build_only do
    xcodebuild(
      scheme: "MoneyBoy",
      workspace: "MoneyBoy.xcworkspace",
      sdk: "iphonesimulator",
      destination: "platform=iOS Simulator,name=iPhone 13,OS=15.2",
      xcargs: "build-for-testing"
    )
  end

  lane :beta do 
    create_keychain(
      name: "#{ENV["KEYCHAIN_NAME"]}",
      password: "#{ENV["KEYCHAIN_PASS"]}",
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )
    app_store_connect_api_key(
      key_id: "#{ENV["PRIVATE_KEY_ID"]}",
      issuer_id: "#{ENV["PRIVATE_KEY_ISSUER"]}",
      key_content: "#{ENV["PRIVATE_KEY_CONTENT"]}",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    match(
      type: "appstore", 
      readonly: is_ci,
      keychain_name: "#{ENV["KEYCHAIN_NAME"]}",
      keychain_password: "#{ENV["KEYCHAIN_PASS"]}"
    )
    update_project_provisioning(
      xcodeproj: "MoneyBoy.xcodeproj",
      profile: "#{ENV["sigh_dev.pesca.app.MoneyBoy_appstore_profile-path"]}", # optional if you use sigh
      build_configuration: "Release",
      code_signing_identity: "iPhone Distribution"
    )
    update_code_signing_settings(
      path: "MoneyBoy.xcodeproj",
      profile_name: "#{ENV["sigh_dev.pesca.app.MoneyBoy_appstore_profile-name"]}",
      profile_uuid: "#{ENV["sigh_dev.pesca.app.MoneyBoy_appstore"]}",
      team_id: "#{ENV["sigh_dev.pesca.app.MoneyBoy_appstore_team-id"]}",
    )
    # set version number to number from env vars
    increment_version_number(
      version_number: ENV["VERSION_NUMBER"]
    )

    # increment build number depending on current build number in testflight
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "MoneyBoy.xcodeproj"
    )

    # build and upload app
    build_app(scheme: "MoneyBoy")
    upload_to_testflight
  end
end
