# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Builds the app without a provisioning profile"
  lane :build_only do
    xcodebuild(
      scheme: "MoneyBoy",
      workspace: "MoneyBoy.xcworkspace",
      sdk: "iphonesimulator",
      destination: "platform=iOS Simulator,name=iPhone 12,OS=14.4",
      xcargs: "build-for-testing"
    )
  end

  # desc "Description of what the lane does"
  # lane :custom_lane do
  #   # add actions here: https://docs.fastlane.tools/actions
  # end

  lane :beta do 
    app_store_connect_api_key(
      key_id: "#{ENV["PRIVATE_KEY_ID"]}",
      issuer_id: "#{ENV["PRIVATE_KEY_ISSUER"]}",
      key_content: "#{ENV["PRIVATE_KEY_CONTENT"]}",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    match(type: "appstore", readonly: is_ci)
    update_project_provisioning(
      xcodeproj: "MoneyBoy.xcodeproj",
      profile: "#{ENV["sigh_dev.pesca.app.MoneyBoy_appstore_profile-path"]}", # optional if you use sigh
      build_configuration: "Release",
      code_signing_identity: "iPhone Distribution"
    )
    update_code_signing_settings(
      path: "MoneyBoy.xcodeproj",
      profile_name: "#{ENV["sigh_dev.pesca.app.MoneyBoy_appstore_profile-name"]}",
      profile_uuid: "#{ENV["sigh_dev.pesca.app.MoneyBoy_appstore"]}",
      team_id: "#{ENV["sigh_dev.pesca.app.MoneyBoy_appstore_team-id"]}",
    )
    # set version number to number from env vars
    increment_version_number(
      version_number: ENV["VERSION_NUMBER"]
    )

    # increment build number depending on current build number in testflight
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "MoneyBoy.xcodeproj"
    )

    # build and upload app
    build_app(scheme: "MoneyBoy")
    upload_to_testflight
  end
end
