#!/usr/bin/env sh

# Checks out the Xcode project again.

if [ -n "$(git status --porcelain)" ]; then
    echo "Please make sure everything is committed!"
    exit 1
fi

cd $(dirname $0)/..

proj_path="$PWD/ios/MoneyBoy.xcodeproj/project.pbxproj"

if [ ! -f "$proj_path" ]; then
    echo "Could not find the Xcode project at $proj_path."
    exit 1
fi

echo "Re-checking out $proj_path"
rm "$proj_path"
git checkout "$proj_path"
