#!/usr/bin/env sh

# Sets up a Git smudge/clean filter that automatically strips
# the Xcode Development Team before the Xcode project is
# added to the staging area and automatically reinserts it upon
# checkout.

DEVTEAM_PLACEHOLDER='iOS Developer'
DEVTEAM_FIELD_PREFIX='DEVELOPMENT_TEAM\s*=\s*'
FILTER_NAME='xcodeTeam'

set -e
cd $(dirname $0)

devteam=$1

if [ -z "$devteam" ]; then
    echo "Usage: $0 [development team id, e.g. XXXXXXXXXX]"
    exit 1
fi

git config filter.$FILTER_NAME.clean "sed 's/\\($DEVTEAM_FIELD_PREFIX\\)\\(\w\+\\)/\1$DEVTEAM_PLACEHOLDER/'"
git config filter.$FILTER_NAME.smudge "sed 's/\\($DEVTEAM_FIELD_PREFIX\\)$DEVTEAM_PLACEHOLDER/\1$devteam/'"

echo "Configured Git filter '$FILTER_NAME' to use team '$devteam'"
echo "You may now want to re-checkout the Xcode project using 'scripts/recheckout-xcodeproj'"
