#!/usr/bin/env python3

# Bootstraps a local development environment.

import argparse
import shutil
import subprocess
import pathlib

# The root directory of the repository
ROOT = pathlib.Path(__file__).absolute().parent.parent

def run(cmd, **kwargs):
    subprocess.run(cmd, cwd=ROOT, check=True, **kwargs)

def main():
    parser = argparse.ArgumentParser(description='Bootstraps a local development environment.')

    parser.add_argument('--ci', action='store_true', help='Uses CI-specific configurations.')
    parser.add_argument('--ios', action='store_true', help='Sets up the environment for iOS.')
    parser.add_argument('--android', action='store_true', help='Sets up the environment for Android.')

    args = parser.parse_args()

    if not shutil.which('npm'):
        print('Please make sure that npm (Node.js) is installed!')
        exit(1)

    if not shutil.which('bundle'):
        print('Please make sure that bundler (Ruby) is installed!')
        exit(1)

    print('==> Installing npm dependencies...')
    if args.ci:
        run(['npm', 'install'])
    else:
        run(['npm', 'ci'])

    print('==> Installing gem dependencies (e.g. fastlane)...')
    run(['bundle', 'install'])

    if args.ios:
        print('==> Setting up iOS environment...')
        run(['scripts/setup-ios'])

    if args.android:
        print('==> Setting up Android environment...')
        run(['scripts/setup-android'])

if __name__ == '__main__':
    main()
