#!/usr/bin/env sh

# Bootstraps an iOS development environment.

set -e
cd $(dirname $0)/..

# Install system dependencies
brew install cocoapods xcodegen

# Set up the Xcode project
cd ios
touch main.jsbundle
xcodegen generate
rm -rf main.jsbundle

# Install CocoaPods dependencies
pod install
